/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-2-gff637a7

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    /* 心跳消费者：sub1 监控右轮(node10)、sub2 监控左轮(node11)。
     * 每槽 32 位 = (nodeId<<16) | 超时ms，0=禁用。1000ms 无心跳 → HBconsumer
     * 自动置 TIMEOUT 并上报 EMCY(库内建)，RT 拍据此降级为零速(见 CO_application.c)。 */
    .x1016_consumerHeartbeatTime = {0x000A03E8, 0x000B03E8, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000},
    .x1017_producerHeartbeatTime = 0x0000,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000200,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000300,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000400,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByRPDO = 0x80000500,
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1603_RPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        .COB_IDUsedByTPDO = 0xC000050A,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0010,
        .eventTimer = 0x0100,
        .SYNCStartValue = 0x80
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x60400010,
        .applicationObject2 = 0x60FF0020,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    .x402C_directDataOperationOperationDataNumber = 0,
    .x402D_directDataOperationOperationType = 0x00,
    .x402E_directDataOperationPosition = 0,
    .x402F_directDataOperationOperatingVelocity = 0,
    .x4030_directDataOperationAccelerationRate = 1000,
    .x4031_directDataOperationDecelerationRate = 1000,
    .x4032_directDataOperationTorqueLimitingValue = 10000,
    .x4033_directDataOperationTrigger = 0,
    .x4034_directDataOperationForwardingDestination = 0x00,
    .x403A_driverInputCommand2nd = 0x00000000,
    .x403C_driverInputCommandAutomaticOFF = 0x00000000,
    .x403E_driverInputCommand = 0x00000000,
    .x404B_targetPositionUser_definedPositionUnit = 0,
    .x40C0_alarmReset = 0x00,
    .x40C2_clearAlarmHistory = 0x00,
    .x40C5_P_PRESETExecution = 0x00,
    .x40C6_configuration = 0x00,
    .x40CD_clearLatchInformation = 0x00,
    .x40CE_clearSequenceHistory = 0x00,
    .x40D0_clearETO = 0x00,
    .x40D1_ZSG_PRESET = 0x00,
    .x40D2_clearZSG_PRESET = 0x00,
    .x40D3_clearInformation = 0x00,
    .x40D6_clearUserEnergyConsumption = 0x00,
    .x40D7_clearTripmeter0 = 0x00,
    .x40D8_clearTripmeter1 = 0x00,
    .x4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates = 0x00,
    .x415F_JOG_HOME_TorqueLimitValue = 0x2710,
    .x4160_HOME_HomingMode = 0x01,
    .x4163_HOME_StartingVelocity = 0x0000001E,
    .x4169_HOME_BackwardStepsIn2SensorHomeseeking = 0x00004650,
    .x4186_stoppingTimeoutAtAlarmGeneration = 0x0BB8,
    .x41CA_WRAPSetting = 0x01,
    .x4735_customStoppingRate = 0x000003E8,
    .x4736_customStoppingTime = 0x000003E8,
    .x6040_controlword = 0x0004,
    .x605A_quickStopOptionCode = 2,
    .x605B_shutdownOptionCode = 0,
    .x605C_disableOperationOptionCode = 1,
    .x605D_haltOptionCode = 1,
    .x605E_faultReactionOptionCode = 2,
    .x6060_modesOfOperation = 3,
    .x6065_followingErrorWindow = 0x0001A5E0,
    .x6067_positionWindow = 0x00000012,
    .x606D_velocityWindow = 0x000F,
    .x606F_velocityThreshold = 0x000F,
    .x6072_maxTorque = 0x2710,
    .x607A_targetPosition = 0,
    .x607B_positionRangeLimit_sub0 = 0x02,
    .x607B_positionRangeLimit = {0, 0},
    .x607C_homeOffset = 0,
    .x607D_softwarePositionLimit_sub0 = 0x02,
    .x607D_softwarePositionLimit = {0, 0},
    .x6081_profileVelocity = 0x00000001,
    .x6082_endVelocity = 0x00000000,
    .x6083_profileAcceleration = 0x000003E8,
    .x6084_profileDeceleration = 0x000003E8,
    .x6085_quickStopDeceleration = 0x000003E8,
    .x608F_positionEncoderResolution_sub0 = 0x02,
    .x608F_positionEncoderResolution = {0x00008CA0, 0x00000001},
    .x6091_gearRatio_sub0 = 0x02,
    .x6091_gearRatio = {0x00000001, 0x00000001},
    .x6098_homingMethod = 37,
    .x6099_homingSpeeds_sub0 = 0x02,
    .x6099_homingSpeeds = {0x0000003C, 0x0000001E},
    .x609A_homingAcceleration = 0x000003E8,
    .x60B8_touchProbeFunction = 0x3131,
    .x60E3_supportedHomingMethods_sub0 = 0x0B,
    .x60E3_supportedHomingMethods = {37, 35, 1, 2, 8, 12, 17, 18, 24, 28, -1},
    .x60F2_positioningOptionCode = 0x0000,
    .x60FE_digitalOutputs_sub0 = 0x01,
    .x60FE_digitalOutputs = {0x00000000},
    .x60FF_targetVelocity = 0,
    .x6502_supportedDriveModes = 0x00000025,
    .x67FE_versionNumber = 0x00040100,
    .x67FF_singleDeviceType = 0x00020192,
    .x6FFF_agvOdometry_sub0 = 0x03,
    .x6FFF_agvOdometry = {0.0f, 0.0f, 0.0f},
    .x7000_agvCmdVel_sub0 = 0x02,
    .x7000_agvCmdVel = {0.0f, 0.0f}
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    OD_obj_var_t o_402C_directDataOperationOperationDataNumber;
    OD_obj_var_t o_402D_directDataOperationOperationType;
    OD_obj_var_t o_402E_directDataOperationPosition;
    OD_obj_var_t o_402F_directDataOperationOperatingVelocity;
    OD_obj_var_t o_4030_directDataOperationAccelerationRate;
    OD_obj_var_t o_4031_directDataOperationDecelerationRate;
    OD_obj_var_t o_4032_directDataOperationTorqueLimitingValue;
    OD_obj_var_t o_4033_directDataOperationTrigger;
    OD_obj_var_t o_4034_directDataOperationForwardingDestination;
    OD_obj_var_t o_403A_driverInputCommand2nd;
    OD_obj_var_t o_403C_driverInputCommandAutomaticOFF;
    OD_obj_var_t o_403D_NETSelectionDataNumber;
    OD_obj_var_t o_403E_driverInputCommand;
    OD_obj_var_t o_403F_driverOutputStatus;
    OD_obj_var_t o_404B_targetPositionUser_definedPositionUnit;
    OD_obj_var_t o_404C_demandPositionUser_definedPositionUnit;
    OD_obj_var_t o_404D_actualPositionUser_definedPositionUnit;
    OD_obj_var_t o_404E_targetVelocityUser_definedVelocityUnit;
    OD_obj_var_t o_404F_demandVelocityUser_definedVelocityUnit;
    OD_obj_var_t o_4050_actualVelocityUser_definedVelocityUnit;
    OD_obj_var_t o_4056_presentCommunicationError;
    OD_obj_var_t o_406B_torqueMonitor;
    OD_obj_var_t o_406C_loadFactorMonitor;
    OD_obj_var_t o_406D_cumulativeLoadMonitor;
    OD_obj_var_t o_4070_nextDataNumber;
    OD_obj_var_t o_4071_loopOriginDataNumber;
    OD_obj_var_t o_4072_loopCount;
    OD_obj_var_t o_4073_positionDeviation;
    OD_obj_var_t o_4075_speedDeviation;
    OD_obj_var_t o_407A_tripmeter1;
    OD_obj_var_t o_407B_presentInformation;
    OD_obj_var_t o_407C_driverTemperature;
    OD_obj_var_t o_407D_motorTemperature;
    OD_obj_var_t o_407E_odometer;
    OD_obj_var_t o_407F_tripmeter0;
    OD_obj_var_t o_409B_mainPowerSupplyCurrent;
    OD_obj_var_t o_409C_powerConsumption;
    OD_obj_var_t o_409D_energyConsumption;
    OD_obj_var_t o_409E_userEnergyConsumption;
    OD_obj_var_t o_409F_totalEnergyConsumption;
    OD_obj_var_t o_40A1_totalUptime;
    OD_obj_var_t o_40A2_numberOfBoots;
    OD_obj_var_t o_40A3_inverterVoltage;
    OD_obj_var_t o_40A4_mainPowerSupplyVoltage;
    OD_obj_var_t o_40A9_continuousUptime;
    OD_obj_var_t o_40AA_RS_485CommunicationReceptionByteCounter;
    OD_obj_var_t o_40AB_RS_485CommunicationTransmissionByteCounter;
    OD_obj_var_t o_40C0_alarmReset;
    OD_obj_var_t o_40C2_clearAlarmHistory;
    OD_obj_var_t o_40C5_P_PRESETExecution;
    OD_obj_var_t o_40C6_configuration;
    OD_obj_var_t o_40CD_clearLatchInformation;
    OD_obj_var_t o_40CE_clearSequenceHistory;
    OD_obj_var_t o_40D0_clearETO;
    OD_obj_var_t o_40D1_ZSG_PRESET;
    OD_obj_var_t o_40D2_clearZSG_PRESET;
    OD_obj_var_t o_40D3_clearInformation;
    OD_obj_var_t o_40D6_clearUserEnergyConsumption;
    OD_obj_var_t o_40D7_clearTripmeter0;
    OD_obj_var_t o_40D8_clearTripmeter1;
    OD_obj_var_t o_4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates;
    OD_obj_var_t o_415F_JOG_HOME_TorqueLimitValue;
    OD_obj_var_t o_4160_HOME_HomingMode;
    OD_obj_var_t o_4163_HOME_StartingVelocity;
    OD_obj_var_t o_4169_HOME_BackwardStepsIn2SensorHomeseeking;
    OD_obj_var_t o_4186_stoppingTimeoutAtAlarmGeneration;
    OD_obj_var_t o_41CA_WRAPSetting;
    OD_obj_var_t o_4735_customStoppingRate;
    OD_obj_var_t o_4736_customStoppingTime;
    OD_obj_var_t o_603F_errorCode;
    OD_obj_var_t o_6040_controlword;
    OD_obj_var_t o_6041_statusword;
    OD_obj_var_t o_605A_quickStopOptionCode;
    OD_obj_var_t o_605B_shutdownOptionCode;
    OD_obj_var_t o_605C_disableOperationOptionCode;
    OD_obj_var_t o_605D_haltOptionCode;
    OD_obj_var_t o_605E_faultReactionOptionCode;
    OD_obj_var_t o_6060_modesOfOperation;
    OD_obj_var_t o_6061_modesOfOperationDisplay;
    OD_obj_var_t o_6062_positionDemandValue;
    OD_obj_var_t o_6064_positionActualValue;
    OD_obj_var_t o_6065_followingErrorWindow;
    OD_obj_var_t o_6067_positionWindow;
    OD_obj_var_t o_606B_velocityDemandValue;
    OD_obj_var_t o_606C_velocityActualValue;
    OD_obj_var_t o_606D_velocityWindow;
    OD_obj_var_t o_606F_velocityThreshold;
    OD_obj_var_t o_6072_maxTorque;
    OD_obj_var_t o_6077_torqueActualValue;
    OD_obj_var_t o_607A_targetPosition;
    OD_obj_array_t o_607B_positionRangeLimit;
    OD_obj_var_t o_607C_homeOffset;
    OD_obj_array_t o_607D_softwarePositionLimit;
    OD_obj_var_t o_6081_profileVelocity;
    OD_obj_var_t o_6082_endVelocity;
    OD_obj_var_t o_6083_profileAcceleration;
    OD_obj_var_t o_6084_profileDeceleration;
    OD_obj_var_t o_6085_quickStopDeceleration;
    OD_obj_array_t o_608F_positionEncoderResolution;
    OD_obj_array_t o_6091_gearRatio;
    OD_obj_var_t o_6098_homingMethod;
    OD_obj_array_t o_6099_homingSpeeds;
    OD_obj_var_t o_609A_homingAcceleration;
    OD_obj_var_t o_60A8_SIUnitPosition;
    OD_obj_var_t o_60A9_SIUnitVelocity;
    OD_obj_var_t o_60B8_touchProbeFunction;
    OD_obj_var_t o_60B9_touchProbeStatus;
    OD_obj_var_t o_60BA_touchProbe1PositiveEdge;
    OD_obj_var_t o_60BB_touchProbe1NegativeEdge;
    OD_obj_var_t o_60BC_touchProbe2PositiveEdge;
    OD_obj_var_t o_60BD_touchProbe2NegativeEdge;
    OD_obj_var_t o_60D5_touchProbe1PositiveEdgeCounter;
    OD_obj_var_t o_60D6_touchProbe1NegativeEdgeCounter;
    OD_obj_var_t o_60D7_touchProbe2PositiveEdgeCounter;
    OD_obj_var_t o_60D8_touchProbe2NegativeEdgeCounter;
    OD_obj_array_t o_60E3_supportedHomingMethods;
    OD_obj_var_t o_60F2_positioningOptionCode;
    OD_obj_var_t o_60F4_followingErrorActualValue;
    OD_obj_var_t o_60FD_digitalInputs;
    OD_obj_array_t o_60FE_digitalOutputs;
    OD_obj_var_t o_60FF_targetVelocity;
    OD_obj_var_t o_6502_supportedDriveModes;
    OD_obj_var_t o_67FE_versionNumber;
    OD_obj_var_t o_67FF_singleDeviceType;
    OD_obj_array_t o_6FFF_agvOdometry;
    OD_obj_array_t o_7000_agvCmdVel;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_402C_directDataOperationOperationDataNumber = {
        .dataOrig = &OD_RAM.x402C_directDataOperationOperationDataNumber,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_402D_directDataOperationOperationType = {
        .dataOrig = &OD_RAM.x402D_directDataOperationOperationType,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_402E_directDataOperationPosition = {
        .dataOrig = &OD_RAM.x402E_directDataOperationPosition,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_402F_directDataOperationOperatingVelocity = {
        .dataOrig = &OD_RAM.x402F_directDataOperationOperatingVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4030_directDataOperationAccelerationRate = {
        .dataOrig = &OD_RAM.x4030_directDataOperationAccelerationRate,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4031_directDataOperationDecelerationRate = {
        .dataOrig = &OD_RAM.x4031_directDataOperationDecelerationRate,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4032_directDataOperationTorqueLimitingValue = {
        .dataOrig = &OD_RAM.x4032_directDataOperationTorqueLimitingValue,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_4033_directDataOperationTrigger = {
        .dataOrig = &OD_RAM.x4033_directDataOperationTrigger,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4034_directDataOperationForwardingDestination = {
        .dataOrig = &OD_RAM.x4034_directDataOperationForwardingDestination,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_403A_driverInputCommand2nd = {
        .dataOrig = &OD_RAM.x403A_driverInputCommand2nd,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_403C_driverInputCommandAutomaticOFF = {
        .dataOrig = &OD_RAM.x403C_driverInputCommandAutomaticOFF,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_403D_NETSelectionDataNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_403E_driverInputCommand = {
        .dataOrig = &OD_RAM.x403E_driverInputCommand,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_403F_driverOutputStatus = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_404B_targetPositionUser_definedPositionUnit = {
        .dataOrig = &OD_RAM.x404B_targetPositionUser_definedPositionUnit,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_404C_demandPositionUser_definedPositionUnit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_404D_actualPositionUser_definedPositionUnit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_404E_targetVelocityUser_definedVelocityUnit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_404F_demandVelocityUser_definedVelocityUnit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4050_actualVelocityUser_definedVelocityUnit = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4056_presentCommunicationError = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_406B_torqueMonitor = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_406C_loadFactorMonitor = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_406D_cumulativeLoadMonitor = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4070_nextDataNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_4071_loopOriginDataNumber = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_4072_loopCount = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4073_positionDeviation = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4075_speedDeviation = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_407A_tripmeter1 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_407B_presentInformation = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_407C_driverTemperature = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_407D_motorTemperature = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_407E_odometer = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_407F_tripmeter0 = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_409B_mainPowerSupplyCurrent = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_409C_powerConsumption = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_409D_energyConsumption = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_409E_userEnergyConsumption = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_409F_totalEnergyConsumption = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40A1_totalUptime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40A2_numberOfBoots = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40A3_inverterVoltage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_40A4_mainPowerSupplyVoltage = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_40A9_continuousUptime = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40AA_RS_485CommunicationReceptionByteCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40AB_RS_485CommunicationTransmissionByteCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_40C0_alarmReset = {
        .dataOrig = &OD_RAM.x40C0_alarmReset,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40C2_clearAlarmHistory = {
        .dataOrig = &OD_RAM.x40C2_clearAlarmHistory,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40C5_P_PRESETExecution = {
        .dataOrig = &OD_RAM.x40C5_P_PRESETExecution,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40C6_configuration = {
        .dataOrig = &OD_RAM.x40C6_configuration,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40CD_clearLatchInformation = {
        .dataOrig = &OD_RAM.x40CD_clearLatchInformation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40CE_clearSequenceHistory = {
        .dataOrig = &OD_RAM.x40CE_clearSequenceHistory,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D0_clearETO = {
        .dataOrig = &OD_RAM.x40D0_clearETO,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D1_ZSG_PRESET = {
        .dataOrig = &OD_RAM.x40D1_ZSG_PRESET,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D2_clearZSG_PRESET = {
        .dataOrig = &OD_RAM.x40D2_clearZSG_PRESET,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D3_clearInformation = {
        .dataOrig = &OD_RAM.x40D3_clearInformation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D6_clearUserEnergyConsumption = {
        .dataOrig = &OD_RAM.x40D6_clearUserEnergyConsumption,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D7_clearTripmeter0 = {
        .dataOrig = &OD_RAM.x40D7_clearTripmeter0,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_40D8_clearTripmeter1 = {
        .dataOrig = &OD_RAM.x40D8_clearTripmeter1,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates = {
        .dataOrig = &OD_RAM.x4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_415F_JOG_HOME_TorqueLimitValue = {
        .dataOrig = &OD_RAM.x415F_JOG_HOME_TorqueLimitValue,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_4160_HOME_HomingMode = {
        .dataOrig = &OD_RAM.x4160_HOME_HomingMode,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_4163_HOME_StartingVelocity = {
        .dataOrig = &OD_RAM.x4163_HOME_StartingVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4169_HOME_BackwardStepsIn2SensorHomeseeking = {
        .dataOrig = &OD_RAM.x4169_HOME_BackwardStepsIn2SensorHomeseeking,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4186_stoppingTimeoutAtAlarmGeneration = {
        .dataOrig = &OD_RAM.x4186_stoppingTimeoutAtAlarmGeneration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_41CA_WRAPSetting = {
        .dataOrig = &OD_RAM.x41CA_WRAPSetting,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_4735_customStoppingRate = {
        .dataOrig = &OD_RAM.x4735_customStoppingRate,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_4736_customStoppingTime = {
        .dataOrig = &OD_RAM.x4736_customStoppingTime,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_603F_errorCode = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6040_controlword = {
        .dataOrig = &OD_RAM.x6040_controlword,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6041_statusword = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_605A_quickStopOptionCode = {
        .dataOrig = &OD_RAM.x605A_quickStopOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605B_shutdownOptionCode = {
        .dataOrig = &OD_RAM.x605B_shutdownOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605C_disableOperationOptionCode = {
        .dataOrig = &OD_RAM.x605C_disableOperationOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605D_haltOptionCode = {
        .dataOrig = &OD_RAM.x605D_haltOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_605E_faultReactionOptionCode = {
        .dataOrig = &OD_RAM.x605E_faultReactionOptionCode,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_6060_modesOfOperation = {
        .dataOrig = &OD_RAM.x6060_modesOfOperation,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6061_modesOfOperationDisplay = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO,
        .dataLength = 1
    },
    .o_6062_positionDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6064_positionActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6065_followingErrorWindow = {
        .dataOrig = &OD_RAM.x6065_followingErrorWindow,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6067_positionWindow = {
        .dataOrig = &OD_RAM.x6067_positionWindow,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606B_velocityDemandValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606C_velocityActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_606D_velocityWindow = {
        .dataOrig = &OD_RAM.x606D_velocityWindow,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_606F_velocityThreshold = {
        .dataOrig = &OD_RAM.x606F_velocityThreshold,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6072_maxTorque = {
        .dataOrig = &OD_RAM.x6072_maxTorque,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_6077_torqueActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_607A_targetPosition = {
        .dataOrig = &OD_RAM.x607A_targetPosition,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607B_positionRangeLimit = {
        .dataOrig0 = &OD_RAM.x607B_positionRangeLimit_sub0,
        .dataOrig = &OD_RAM.x607B_positionRangeLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_607C_homeOffset = {
        .dataOrig = &OD_RAM.x607C_homeOffset,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_607D_softwarePositionLimit = {
        .dataOrig0 = &OD_RAM.x607D_softwarePositionLimit_sub0,
        .dataOrig = &OD_RAM.x607D_softwarePositionLimit[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(int32_t)
    },
    .o_6081_profileVelocity = {
        .dataOrig = &OD_RAM.x6081_profileVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6082_endVelocity = {
        .dataOrig = &OD_RAM.x6082_endVelocity,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6083_profileAcceleration = {
        .dataOrig = &OD_RAM.x6083_profileAcceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6084_profileDeceleration = {
        .dataOrig = &OD_RAM.x6084_profileDeceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6085_quickStopDeceleration = {
        .dataOrig = &OD_RAM.x6085_quickStopDeceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_608F_positionEncoderResolution = {
        .dataOrig0 = &OD_RAM.x608F_positionEncoderResolution_sub0,
        .dataOrig = &OD_RAM.x608F_positionEncoderResolution[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6091_gearRatio = {
        .dataOrig0 = &OD_RAM.x6091_gearRatio_sub0,
        .dataOrig = &OD_RAM.x6091_gearRatio[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_6098_homingMethod = {
        .dataOrig = &OD_RAM.x6098_homingMethod,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    .o_6099_homingSpeeds = {
        .dataOrig0 = &OD_RAM.x6099_homingSpeeds_sub0,
        .dataOrig = &OD_RAM.x6099_homingSpeeds[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_609A_homingAcceleration = {
        .dataOrig = &OD_RAM.x609A_homingAcceleration,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60A8_SIUnitPosition = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60A9_SIUnitVelocity = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_60B8_touchProbeFunction = {
        .dataOrig = &OD_RAM.x60B8_touchProbeFunction,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60B9_touchProbeStatus = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60BA_touchProbe1PositiveEdge = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60BB_touchProbe1NegativeEdge = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60BC_touchProbe2PositiveEdge = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60BD_touchProbe2NegativeEdge = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60D5_touchProbe1PositiveEdgeCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60D6_touchProbe1NegativeEdgeCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60D7_touchProbe2PositiveEdgeCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60D8_touchProbe2NegativeEdgeCounter = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60E3_supportedHomingMethods = {
        .dataOrig0 = &OD_RAM.x60E3_supportedHomingMethods_sub0,
        .dataOrig = &OD_RAM.x60E3_supportedHomingMethods[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R,
        .dataElementLength = 1,
        .dataElementSizeof = sizeof(int8_t)
    },
    .o_60F2_positioningOptionCode = {
        .dataOrig = &OD_RAM.x60F2_positioningOptionCode,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    .o_60F4_followingErrorActualValue = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FD_digitalInputs = {
        .dataOrig = NULL,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_60FE_digitalOutputs = {
        .dataOrig0 = &OD_RAM.x60FE_digitalOutputs_sub0,
        .dataOrig = &OD_RAM.x60FE_digitalOutputs[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_RPDO | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_60FF_targetVelocity = {
        .dataOrig = &OD_RAM.x60FF_targetVelocity,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    .o_6502_supportedDriveModes = {
        .dataOrig = &OD_RAM.x6502_supportedDriveModes,
        .attribute = ODA_SDO_R | ODA_TRPDO | ODA_MB,
        .dataLength = 4
    },
    .o_67FE_versionNumber = {
        .dataOrig = &OD_RAM.x67FE_versionNumber,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_67FF_singleDeviceType = {
        .dataOrig = &OD_RAM.x67FF_singleDeviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_6FFF_agvOdometry = {
        .dataOrig0 = &OD_RAM.x6FFF_agvOdometry_sub0,
        .dataOrig = &OD_RAM.x6FFF_agvOdometry[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    },
    .o_7000_agvCmdVel = {
        .dataOrig0 = &OD_RAM.x7000_agvCmdVel_sub0,
        .dataOrig = &OD_RAM.x7000_agvCmdVel[0],
        .attribute0 = ODA_SDO_R,
        /* SDO 可写：由上位机经网关下发 cmd_vel；RT 侧读。 */
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(float32_t)
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    {0x402C, 0x01, ODT_VAR, &ODObjs.o_402C_directDataOperationOperationDataNumber, NULL},
    {0x402D, 0x01, ODT_VAR, &ODObjs.o_402D_directDataOperationOperationType, NULL},
    {0x402E, 0x01, ODT_VAR, &ODObjs.o_402E_directDataOperationPosition, NULL},
    {0x402F, 0x01, ODT_VAR, &ODObjs.o_402F_directDataOperationOperatingVelocity, NULL},
    {0x4030, 0x01, ODT_VAR, &ODObjs.o_4030_directDataOperationAccelerationRate, NULL},
    {0x4031, 0x01, ODT_VAR, &ODObjs.o_4031_directDataOperationDecelerationRate, NULL},
    {0x4032, 0x01, ODT_VAR, &ODObjs.o_4032_directDataOperationTorqueLimitingValue, NULL},
    {0x4033, 0x01, ODT_VAR, &ODObjs.o_4033_directDataOperationTrigger, NULL},
    {0x4034, 0x01, ODT_VAR, &ODObjs.o_4034_directDataOperationForwardingDestination, NULL},
    {0x403A, 0x01, ODT_VAR, &ODObjs.o_403A_driverInputCommand2nd, NULL},
    {0x403C, 0x01, ODT_VAR, &ODObjs.o_403C_driverInputCommandAutomaticOFF, NULL},
    {0x403D, 0x01, ODT_VAR, &ODObjs.o_403D_NETSelectionDataNumber, NULL},
    {0x403E, 0x01, ODT_VAR, &ODObjs.o_403E_driverInputCommand, NULL},
    {0x403F, 0x01, ODT_VAR, &ODObjs.o_403F_driverOutputStatus, NULL},
    {0x404B, 0x01, ODT_VAR, &ODObjs.o_404B_targetPositionUser_definedPositionUnit, NULL},
    {0x404C, 0x01, ODT_VAR, &ODObjs.o_404C_demandPositionUser_definedPositionUnit, NULL},
    {0x404D, 0x01, ODT_VAR, &ODObjs.o_404D_actualPositionUser_definedPositionUnit, NULL},
    {0x404E, 0x01, ODT_VAR, &ODObjs.o_404E_targetVelocityUser_definedVelocityUnit, NULL},
    {0x404F, 0x01, ODT_VAR, &ODObjs.o_404F_demandVelocityUser_definedVelocityUnit, NULL},
    {0x4050, 0x01, ODT_VAR, &ODObjs.o_4050_actualVelocityUser_definedVelocityUnit, NULL},
    {0x4056, 0x01, ODT_VAR, &ODObjs.o_4056_presentCommunicationError, NULL},
    {0x406B, 0x01, ODT_VAR, &ODObjs.o_406B_torqueMonitor, NULL},
    {0x406C, 0x01, ODT_VAR, &ODObjs.o_406C_loadFactorMonitor, NULL},
    {0x406D, 0x01, ODT_VAR, &ODObjs.o_406D_cumulativeLoadMonitor, NULL},
    {0x4070, 0x01, ODT_VAR, &ODObjs.o_4070_nextDataNumber, NULL},
    {0x4071, 0x01, ODT_VAR, &ODObjs.o_4071_loopOriginDataNumber, NULL},
    {0x4072, 0x01, ODT_VAR, &ODObjs.o_4072_loopCount, NULL},
    {0x4073, 0x01, ODT_VAR, &ODObjs.o_4073_positionDeviation, NULL},
    {0x4075, 0x01, ODT_VAR, &ODObjs.o_4075_speedDeviation, NULL},
    {0x407A, 0x01, ODT_VAR, &ODObjs.o_407A_tripmeter1, NULL},
    {0x407B, 0x01, ODT_VAR, &ODObjs.o_407B_presentInformation, NULL},
    {0x407C, 0x01, ODT_VAR, &ODObjs.o_407C_driverTemperature, NULL},
    {0x407D, 0x01, ODT_VAR, &ODObjs.o_407D_motorTemperature, NULL},
    {0x407E, 0x01, ODT_VAR, &ODObjs.o_407E_odometer, NULL},
    {0x407F, 0x01, ODT_VAR, &ODObjs.o_407F_tripmeter0, NULL},
    {0x409B, 0x01, ODT_VAR, &ODObjs.o_409B_mainPowerSupplyCurrent, NULL},
    {0x409C, 0x01, ODT_VAR, &ODObjs.o_409C_powerConsumption, NULL},
    {0x409D, 0x01, ODT_VAR, &ODObjs.o_409D_energyConsumption, NULL},
    {0x409E, 0x01, ODT_VAR, &ODObjs.o_409E_userEnergyConsumption, NULL},
    {0x409F, 0x01, ODT_VAR, &ODObjs.o_409F_totalEnergyConsumption, NULL},
    {0x40A1, 0x01, ODT_VAR, &ODObjs.o_40A1_totalUptime, NULL},
    {0x40A2, 0x01, ODT_VAR, &ODObjs.o_40A2_numberOfBoots, NULL},
    {0x40A3, 0x01, ODT_VAR, &ODObjs.o_40A3_inverterVoltage, NULL},
    {0x40A4, 0x01, ODT_VAR, &ODObjs.o_40A4_mainPowerSupplyVoltage, NULL},
    {0x40A9, 0x01, ODT_VAR, &ODObjs.o_40A9_continuousUptime, NULL},
    {0x40AA, 0x01, ODT_VAR, &ODObjs.o_40AA_RS_485CommunicationReceptionByteCounter, NULL},
    {0x40AB, 0x01, ODT_VAR, &ODObjs.o_40AB_RS_485CommunicationTransmissionByteCounter, NULL},
    {0x40C0, 0x01, ODT_VAR, &ODObjs.o_40C0_alarmReset, NULL},
    {0x40C2, 0x01, ODT_VAR, &ODObjs.o_40C2_clearAlarmHistory, NULL},
    {0x40C5, 0x01, ODT_VAR, &ODObjs.o_40C5_P_PRESETExecution, NULL},
    {0x40C6, 0x01, ODT_VAR, &ODObjs.o_40C6_configuration, NULL},
    {0x40CD, 0x01, ODT_VAR, &ODObjs.o_40CD_clearLatchInformation, NULL},
    {0x40CE, 0x01, ODT_VAR, &ODObjs.o_40CE_clearSequenceHistory, NULL},
    {0x40D0, 0x01, ODT_VAR, &ODObjs.o_40D0_clearETO, NULL},
    {0x40D1, 0x01, ODT_VAR, &ODObjs.o_40D1_ZSG_PRESET, NULL},
    {0x40D2, 0x01, ODT_VAR, &ODObjs.o_40D2_clearZSG_PRESET, NULL},
    {0x40D3, 0x01, ODT_VAR, &ODObjs.o_40D3_clearInformation, NULL},
    {0x40D6, 0x01, ODT_VAR, &ODObjs.o_40D6_clearUserEnergyConsumption, NULL},
    {0x40D7, 0x01, ODT_VAR, &ODObjs.o_40D7_clearTripmeter0, NULL},
    {0x40D8, 0x01, ODT_VAR, &ODObjs.o_40D8_clearTripmeter1, NULL},
    {0x4148, 0x01, ODT_VAR, &ODObjs.o_4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates, NULL},
    {0x415F, 0x01, ODT_VAR, &ODObjs.o_415F_JOG_HOME_TorqueLimitValue, NULL},
    {0x4160, 0x01, ODT_VAR, &ODObjs.o_4160_HOME_HomingMode, NULL},
    {0x4163, 0x01, ODT_VAR, &ODObjs.o_4163_HOME_StartingVelocity, NULL},
    {0x4169, 0x01, ODT_VAR, &ODObjs.o_4169_HOME_BackwardStepsIn2SensorHomeseeking, NULL},
    {0x4186, 0x01, ODT_VAR, &ODObjs.o_4186_stoppingTimeoutAtAlarmGeneration, NULL},
    {0x41CA, 0x01, ODT_VAR, &ODObjs.o_41CA_WRAPSetting, NULL},
    {0x4735, 0x01, ODT_VAR, &ODObjs.o_4735_customStoppingRate, NULL},
    {0x4736, 0x01, ODT_VAR, &ODObjs.o_4736_customStoppingTime, NULL},
    {0x603F, 0x01, ODT_VAR, &ODObjs.o_603F_errorCode, NULL},
    {0x6040, 0x01, ODT_VAR, &ODObjs.o_6040_controlword, NULL},
    {0x6041, 0x01, ODT_VAR, &ODObjs.o_6041_statusword, NULL},
    {0x605A, 0x01, ODT_VAR, &ODObjs.o_605A_quickStopOptionCode, NULL},
    {0x605B, 0x01, ODT_VAR, &ODObjs.o_605B_shutdownOptionCode, NULL},
    {0x605C, 0x01, ODT_VAR, &ODObjs.o_605C_disableOperationOptionCode, NULL},
    {0x605D, 0x01, ODT_VAR, &ODObjs.o_605D_haltOptionCode, NULL},
    {0x605E, 0x01, ODT_VAR, &ODObjs.o_605E_faultReactionOptionCode, NULL},
    {0x6060, 0x01, ODT_VAR, &ODObjs.o_6060_modesOfOperation, NULL},
    {0x6061, 0x01, ODT_VAR, &ODObjs.o_6061_modesOfOperationDisplay, NULL},
    {0x6062, 0x01, ODT_VAR, &ODObjs.o_6062_positionDemandValue, NULL},
    {0x6064, 0x01, ODT_VAR, &ODObjs.o_6064_positionActualValue, NULL},
    {0x6065, 0x01, ODT_VAR, &ODObjs.o_6065_followingErrorWindow, NULL},
    {0x6067, 0x01, ODT_VAR, &ODObjs.o_6067_positionWindow, NULL},
    {0x606B, 0x01, ODT_VAR, &ODObjs.o_606B_velocityDemandValue, NULL},
    {0x606C, 0x01, ODT_VAR, &ODObjs.o_606C_velocityActualValue, NULL},
    {0x606D, 0x01, ODT_VAR, &ODObjs.o_606D_velocityWindow, NULL},
    {0x606F, 0x01, ODT_VAR, &ODObjs.o_606F_velocityThreshold, NULL},
    {0x6072, 0x01, ODT_VAR, &ODObjs.o_6072_maxTorque, NULL},
    {0x6077, 0x01, ODT_VAR, &ODObjs.o_6077_torqueActualValue, NULL},
    {0x607A, 0x01, ODT_VAR, &ODObjs.o_607A_targetPosition, NULL},
    {0x607B, 0x03, ODT_ARR, &ODObjs.o_607B_positionRangeLimit, NULL},
    {0x607C, 0x01, ODT_VAR, &ODObjs.o_607C_homeOffset, NULL},
    {0x607D, 0x03, ODT_ARR, &ODObjs.o_607D_softwarePositionLimit, NULL},
    {0x6081, 0x01, ODT_VAR, &ODObjs.o_6081_profileVelocity, NULL},
    {0x6082, 0x01, ODT_VAR, &ODObjs.o_6082_endVelocity, NULL},
    {0x6083, 0x01, ODT_VAR, &ODObjs.o_6083_profileAcceleration, NULL},
    {0x6084, 0x01, ODT_VAR, &ODObjs.o_6084_profileDeceleration, NULL},
    {0x6085, 0x01, ODT_VAR, &ODObjs.o_6085_quickStopDeceleration, NULL},
    {0x608F, 0x03, ODT_ARR, &ODObjs.o_608F_positionEncoderResolution, NULL},
    {0x6091, 0x03, ODT_ARR, &ODObjs.o_6091_gearRatio, NULL},
    {0x6098, 0x01, ODT_VAR, &ODObjs.o_6098_homingMethod, NULL},
    {0x6099, 0x03, ODT_ARR, &ODObjs.o_6099_homingSpeeds, NULL},
    {0x609A, 0x01, ODT_VAR, &ODObjs.o_609A_homingAcceleration, NULL},
    {0x60A8, 0x01, ODT_VAR, &ODObjs.o_60A8_SIUnitPosition, NULL},
    {0x60A9, 0x01, ODT_VAR, &ODObjs.o_60A9_SIUnitVelocity, NULL},
    {0x60B8, 0x01, ODT_VAR, &ODObjs.o_60B8_touchProbeFunction, NULL},
    {0x60B9, 0x01, ODT_VAR, &ODObjs.o_60B9_touchProbeStatus, NULL},
    {0x60BA, 0x01, ODT_VAR, &ODObjs.o_60BA_touchProbe1PositiveEdge, NULL},
    {0x60BB, 0x01, ODT_VAR, &ODObjs.o_60BB_touchProbe1NegativeEdge, NULL},
    {0x60BC, 0x01, ODT_VAR, &ODObjs.o_60BC_touchProbe2PositiveEdge, NULL},
    {0x60BD, 0x01, ODT_VAR, &ODObjs.o_60BD_touchProbe2NegativeEdge, NULL},
    {0x60D5, 0x01, ODT_VAR, &ODObjs.o_60D5_touchProbe1PositiveEdgeCounter, NULL},
    {0x60D6, 0x01, ODT_VAR, &ODObjs.o_60D6_touchProbe1NegativeEdgeCounter, NULL},
    {0x60D7, 0x01, ODT_VAR, &ODObjs.o_60D7_touchProbe2PositiveEdgeCounter, NULL},
    {0x60D8, 0x01, ODT_VAR, &ODObjs.o_60D8_touchProbe2NegativeEdgeCounter, NULL},
    {0x60E3, 0x0C, ODT_ARR, &ODObjs.o_60E3_supportedHomingMethods, NULL},
    {0x60F2, 0x01, ODT_VAR, &ODObjs.o_60F2_positioningOptionCode, NULL},
    {0x60F4, 0x01, ODT_VAR, &ODObjs.o_60F4_followingErrorActualValue, NULL},
    {0x60FD, 0x01, ODT_VAR, &ODObjs.o_60FD_digitalInputs, NULL},
    {0x60FE, 0x02, ODT_ARR, &ODObjs.o_60FE_digitalOutputs, NULL},
    {0x60FF, 0x01, ODT_VAR, &ODObjs.o_60FF_targetVelocity, NULL},
    {0x6502, 0x01, ODT_VAR, &ODObjs.o_6502_supportedDriveModes, NULL},
    {0x67FE, 0x01, ODT_VAR, &ODObjs.o_67FE_versionNumber, NULL},
    {0x67FF, 0x01, ODT_VAR, &ODObjs.o_67FF_singleDeviceType, NULL},
    /* 追加在末尾: 0x6FFF > 所有既有索引, 保持 ODList 升序 (OD_find 二分查找)。
     * 第二字段 = 子索引总数 = 数组元素数 + 1 (含 sub0)。 */
    {0x6FFF, 0x04, ODT_ARR, &ODObjs.o_6FFF_agvOdometry, NULL},
    /* 0x7000 cmd_vel：同样追加在末尾，保持 ODList 升序(0x7000 > 0x6FFF)。 */
    {0x7000, 0x03, ODT_ARR, &ODObjs.o_7000_agvCmdVel, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
