/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-2-gff637a7

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: BLVD-KRD-R.xdd
        File Version: 2

        Created:      2022/03/28 14:27:00
        Created By:   ORIENTAL MOTOR Co., Ltd.
        Modified:     2023/05/31 20:01:38
        Modified By:  ORIENTAL MOTOR Co., Ltd.

    Device Info:
        Vendor Name:  ORIENTAL MOTOR Co., Ltd.
        Vendor ID:    702
        Product Name: BLVD-KRD
        Product ID:   5111

        Description:  EDS for BLVD-KRD
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
#define OD_CNT_ARR_607B 2
#define OD_CNT_ARR_607D 2
#define OD_CNT_ARR_608F 2
#define OD_CNT_ARR_6091 2
#define OD_CNT_ARR_6099 2
#define OD_CNT_ARR_60E3 11
#define OD_CNT_ARR_60FE 1
#define OD_CNT_ARR_6FFF 3
#define OD_CNT_ARR_7000 2


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint32_t x1005_COB_ID_SYNCMessage;
    uint32_t x1006_communicationCyclePeriod;
    uint32_t x1007_synchronousWindowLength;
    uint32_t x1012_COB_IDTimeStampObject;
    uint32_t x1014_COB_ID_EMCY;
    uint16_t x1015_inhibitTimeEMCY;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    uint8_t x1019_synchronousCounterOverflowValue;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerTx;
        uint32_t COB_IDServerToClientRx;
        uint8_t node_IDOfTheSDOServer;
    } x1280_SDOClientParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1401_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1402_RPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1403_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1601_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1602_RPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1603_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1802_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1803_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A02_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A03_TPDOMappingParameter;
} OD_PERSIST_COMM_t;

typedef struct {
    uint8_t x1001_errorRegister;
    uint8_t x1010_storeParameters_sub0;
    uint32_t x1010_storeParameters[OD_CNT_ARR_1010];
    uint8_t x1011_restoreDefaultParameters_sub0;
    uint32_t x1011_restoreDefaultParameters[OD_CNT_ARR_1011];
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    int16_t x402C_directDataOperationOperationDataNumber;
    uint8_t x402D_directDataOperationOperationType;
    int32_t x402E_directDataOperationPosition;
    int32_t x402F_directDataOperationOperatingVelocity;
    int32_t x4030_directDataOperationAccelerationRate;
    int32_t x4031_directDataOperationDecelerationRate;
    int16_t x4032_directDataOperationTorqueLimitingValue;
    int32_t x4033_directDataOperationTrigger;
    uint8_t x4034_directDataOperationForwardingDestination;
    uint32_t x403A_driverInputCommand2nd;
    uint32_t x403C_driverInputCommandAutomaticOFF;
    uint32_t x403E_driverInputCommand;
    int32_t x404B_targetPositionUser_definedPositionUnit;
    uint8_t x40C0_alarmReset;
    uint8_t x40C2_clearAlarmHistory;
    uint8_t x40C5_P_PRESETExecution;
    uint8_t x40C6_configuration;
    uint8_t x40CD_clearLatchInformation;
    uint8_t x40CE_clearSequenceHistory;
    uint8_t x40D0_clearETO;
    uint8_t x40D1_ZSG_PRESET;
    uint8_t x40D2_clearZSG_PRESET;
    uint8_t x40D3_clearInformation;
    uint8_t x40D6_clearUserEnergyConsumption;
    uint8_t x40D7_clearTripmeter0;
    uint8_t x40D8_clearTripmeter1;
    uint8_t x4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates;
    uint16_t x415F_JOG_HOME_TorqueLimitValue;
    uint8_t x4160_HOME_HomingMode;
    uint32_t x4163_HOME_StartingVelocity;
    uint32_t x4169_HOME_BackwardStepsIn2SensorHomeseeking;
    uint16_t x4186_stoppingTimeoutAtAlarmGeneration;
    uint8_t x41CA_WRAPSetting;
    uint32_t x4735_customStoppingRate;
    uint32_t x4736_customStoppingTime;
    uint16_t x6040_controlword;
    int16_t x605A_quickStopOptionCode;
    int16_t x605B_shutdownOptionCode;
    int16_t x605C_disableOperationOptionCode;
    int16_t x605D_haltOptionCode;
    int16_t x605E_faultReactionOptionCode;
    int8_t x6060_modesOfOperation;
    uint32_t x6065_followingErrorWindow;
    uint32_t x6067_positionWindow;
    uint16_t x606D_velocityWindow;
    uint16_t x606F_velocityThreshold;
    uint16_t x6072_maxTorque;
    int32_t x607A_targetPosition;
    uint8_t x607B_positionRangeLimit_sub0;
    int32_t x607B_positionRangeLimit[OD_CNT_ARR_607B];
    int32_t x607C_homeOffset;
    uint8_t x607D_softwarePositionLimit_sub0;
    int32_t x607D_softwarePositionLimit[OD_CNT_ARR_607D];
    uint32_t x6081_profileVelocity;
    uint32_t x6082_endVelocity;
    uint32_t x6083_profileAcceleration;
    uint32_t x6084_profileDeceleration;
    uint32_t x6085_quickStopDeceleration;
    uint8_t x608F_positionEncoderResolution_sub0;
    uint32_t x608F_positionEncoderResolution[OD_CNT_ARR_608F];
    uint8_t x6091_gearRatio_sub0;
    uint32_t x6091_gearRatio[OD_CNT_ARR_6091];
    int8_t x6098_homingMethod;
    uint8_t x6099_homingSpeeds_sub0;
    uint32_t x6099_homingSpeeds[OD_CNT_ARR_6099];
    uint32_t x609A_homingAcceleration;
    uint16_t x60B8_touchProbeFunction;
    uint8_t x60E3_supportedHomingMethods_sub0;
    int8_t x60E3_supportedHomingMethods[OD_CNT_ARR_60E3];
    uint16_t x60F2_positioningOptionCode;
    uint8_t x60FE_digitalOutputs_sub0;
    uint32_t x60FE_digitalOutputs[OD_CNT_ARR_60FE];
    int32_t x60FF_targetVelocity;
    uint32_t x6502_supportedDriveModes;
    uint32_t x67FE_versionNumber;
    uint32_t x67FF_singleDeviceType;
    uint8_t x6FFF_agvOdometry_sub0;
    float32_t x6FFF_agvOdometry[OD_CNT_ARR_6FFF];
    /* 第 11 站：上层下发的期望速度 cmd_vel。sub1=线速度 v(m/s), sub2=角速度 ω(rad/s)。
     * 追加在末尾(0x7000 > 0x6FFF)，保持 OD_RAM 成员顺序与 CANopenEditor 生成风格一致。 */
    uint8_t x7000_agvCmdVel_sub0;
    float32_t x7000_agvCmdVel[OD_CNT_ARR_7000];
} OD_RAM_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif
extern OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1003 &OD->list[2]
#define OD_ENTRY_H1005 &OD->list[3]
#define OD_ENTRY_H1006 &OD->list[4]
#define OD_ENTRY_H1007 &OD->list[5]
#define OD_ENTRY_H1010 &OD->list[6]
#define OD_ENTRY_H1011 &OD->list[7]
#define OD_ENTRY_H1012 &OD->list[8]
#define OD_ENTRY_H1014 &OD->list[9]
#define OD_ENTRY_H1015 &OD->list[10]
#define OD_ENTRY_H1016 &OD->list[11]
#define OD_ENTRY_H1017 &OD->list[12]
#define OD_ENTRY_H1018 &OD->list[13]
#define OD_ENTRY_H1019 &OD->list[14]
#define OD_ENTRY_H1200 &OD->list[15]
#define OD_ENTRY_H1280 &OD->list[16]
#define OD_ENTRY_H1400 &OD->list[17]
#define OD_ENTRY_H1401 &OD->list[18]
#define OD_ENTRY_H1402 &OD->list[19]
#define OD_ENTRY_H1403 &OD->list[20]
#define OD_ENTRY_H1600 &OD->list[21]
#define OD_ENTRY_H1601 &OD->list[22]
#define OD_ENTRY_H1602 &OD->list[23]
#define OD_ENTRY_H1603 &OD->list[24]
#define OD_ENTRY_H1800 &OD->list[25]
#define OD_ENTRY_H1801 &OD->list[26]
#define OD_ENTRY_H1802 &OD->list[27]
#define OD_ENTRY_H1803 &OD->list[28]
#define OD_ENTRY_H1A00 &OD->list[29]
#define OD_ENTRY_H1A01 &OD->list[30]
#define OD_ENTRY_H1A02 &OD->list[31]
#define OD_ENTRY_H1A03 &OD->list[32]
#define OD_ENTRY_H402C &OD->list[33]
#define OD_ENTRY_H402D &OD->list[34]
#define OD_ENTRY_H402E &OD->list[35]
#define OD_ENTRY_H402F &OD->list[36]
#define OD_ENTRY_H4030 &OD->list[37]
#define OD_ENTRY_H4031 &OD->list[38]
#define OD_ENTRY_H4032 &OD->list[39]
#define OD_ENTRY_H4033 &OD->list[40]
#define OD_ENTRY_H4034 &OD->list[41]
#define OD_ENTRY_H403A &OD->list[42]
#define OD_ENTRY_H403C &OD->list[43]
#define OD_ENTRY_H403D &OD->list[44]
#define OD_ENTRY_H403E &OD->list[45]
#define OD_ENTRY_H403F &OD->list[46]
#define OD_ENTRY_H404B &OD->list[47]
#define OD_ENTRY_H404C &OD->list[48]
#define OD_ENTRY_H404D &OD->list[49]
#define OD_ENTRY_H404E &OD->list[50]
#define OD_ENTRY_H404F &OD->list[51]
#define OD_ENTRY_H4050 &OD->list[52]
#define OD_ENTRY_H4056 &OD->list[53]
#define OD_ENTRY_H406B &OD->list[54]
#define OD_ENTRY_H406C &OD->list[55]
#define OD_ENTRY_H406D &OD->list[56]
#define OD_ENTRY_H4070 &OD->list[57]
#define OD_ENTRY_H4071 &OD->list[58]
#define OD_ENTRY_H4072 &OD->list[59]
#define OD_ENTRY_H4073 &OD->list[60]
#define OD_ENTRY_H4075 &OD->list[61]
#define OD_ENTRY_H407A &OD->list[62]
#define OD_ENTRY_H407B &OD->list[63]
#define OD_ENTRY_H407C &OD->list[64]
#define OD_ENTRY_H407D &OD->list[65]
#define OD_ENTRY_H407E &OD->list[66]
#define OD_ENTRY_H407F &OD->list[67]
#define OD_ENTRY_H409B &OD->list[68]
#define OD_ENTRY_H409C &OD->list[69]
#define OD_ENTRY_H409D &OD->list[70]
#define OD_ENTRY_H409E &OD->list[71]
#define OD_ENTRY_H409F &OD->list[72]
#define OD_ENTRY_H40A1 &OD->list[73]
#define OD_ENTRY_H40A2 &OD->list[74]
#define OD_ENTRY_H40A3 &OD->list[75]
#define OD_ENTRY_H40A4 &OD->list[76]
#define OD_ENTRY_H40A9 &OD->list[77]
#define OD_ENTRY_H40AA &OD->list[78]
#define OD_ENTRY_H40AB &OD->list[79]
#define OD_ENTRY_H40C0 &OD->list[80]
#define OD_ENTRY_H40C2 &OD->list[81]
#define OD_ENTRY_H40C5 &OD->list[82]
#define OD_ENTRY_H40C6 &OD->list[83]
#define OD_ENTRY_H40CD &OD->list[84]
#define OD_ENTRY_H40CE &OD->list[85]
#define OD_ENTRY_H40D0 &OD->list[86]
#define OD_ENTRY_H40D1 &OD->list[87]
#define OD_ENTRY_H40D2 &OD->list[88]
#define OD_ENTRY_H40D3 &OD->list[89]
#define OD_ENTRY_H40D6 &OD->list[90]
#define OD_ENTRY_H40D7 &OD->list[91]
#define OD_ENTRY_H40D8 &OD->list[92]
#define OD_ENTRY_H4148 &OD->list[93]
#define OD_ENTRY_H415F &OD->list[94]
#define OD_ENTRY_H4160 &OD->list[95]
#define OD_ENTRY_H4163 &OD->list[96]
#define OD_ENTRY_H4169 &OD->list[97]
#define OD_ENTRY_H4186 &OD->list[98]
#define OD_ENTRY_H41CA &OD->list[99]
#define OD_ENTRY_H4735 &OD->list[100]
#define OD_ENTRY_H4736 &OD->list[101]
#define OD_ENTRY_H603F &OD->list[102]
#define OD_ENTRY_H6040 &OD->list[103]
#define OD_ENTRY_H6041 &OD->list[104]
#define OD_ENTRY_H605A &OD->list[105]
#define OD_ENTRY_H605B &OD->list[106]
#define OD_ENTRY_H605C &OD->list[107]
#define OD_ENTRY_H605D &OD->list[108]
#define OD_ENTRY_H605E &OD->list[109]
#define OD_ENTRY_H6060 &OD->list[110]
#define OD_ENTRY_H6061 &OD->list[111]
#define OD_ENTRY_H6062 &OD->list[112]
#define OD_ENTRY_H6064 &OD->list[113]
#define OD_ENTRY_H6065 &OD->list[114]
#define OD_ENTRY_H6067 &OD->list[115]
#define OD_ENTRY_H606B &OD->list[116]
#define OD_ENTRY_H606C &OD->list[117]
#define OD_ENTRY_H606D &OD->list[118]
#define OD_ENTRY_H606F &OD->list[119]
#define OD_ENTRY_H6072 &OD->list[120]
#define OD_ENTRY_H6077 &OD->list[121]
#define OD_ENTRY_H607A &OD->list[122]
#define OD_ENTRY_H607B &OD->list[123]
#define OD_ENTRY_H607C &OD->list[124]
#define OD_ENTRY_H607D &OD->list[125]
#define OD_ENTRY_H6081 &OD->list[126]
#define OD_ENTRY_H6082 &OD->list[127]
#define OD_ENTRY_H6083 &OD->list[128]
#define OD_ENTRY_H6084 &OD->list[129]
#define OD_ENTRY_H6085 &OD->list[130]
#define OD_ENTRY_H608F &OD->list[131]
#define OD_ENTRY_H6091 &OD->list[132]
#define OD_ENTRY_H6098 &OD->list[133]
#define OD_ENTRY_H6099 &OD->list[134]
#define OD_ENTRY_H609A &OD->list[135]
#define OD_ENTRY_H60A8 &OD->list[136]
#define OD_ENTRY_H60A9 &OD->list[137]
#define OD_ENTRY_H60B8 &OD->list[138]
#define OD_ENTRY_H60B9 &OD->list[139]
#define OD_ENTRY_H60BA &OD->list[140]
#define OD_ENTRY_H60BB &OD->list[141]
#define OD_ENTRY_H60BC &OD->list[142]
#define OD_ENTRY_H60BD &OD->list[143]
#define OD_ENTRY_H60D5 &OD->list[144]
#define OD_ENTRY_H60D6 &OD->list[145]
#define OD_ENTRY_H60D7 &OD->list[146]
#define OD_ENTRY_H60D8 &OD->list[147]
#define OD_ENTRY_H60E3 &OD->list[148]
#define OD_ENTRY_H60F2 &OD->list[149]
#define OD_ENTRY_H60F4 &OD->list[150]
#define OD_ENTRY_H60FD &OD->list[151]
#define OD_ENTRY_H60FE &OD->list[152]
#define OD_ENTRY_H60FF &OD->list[153]
#define OD_ENTRY_H6502 &OD->list[154]
#define OD_ENTRY_H67FE &OD->list[155]
#define OD_ENTRY_H67FF &OD->list[156]
/* 自定义条目追加在 ODList[] 末尾, 索引 0x6FFF 大于所有既有索引,
 * 保证 ODList[] 仍按 index 升序 (OD_find 是二分查找). */
#define OD_ENTRY_H6FFF &OD->list[157]
#define OD_ENTRY_H7000 &OD->list[158]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[2]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage &OD->list[3]
#define OD_ENTRY_H1006_communicationCyclePeriod &OD->list[4]
#define OD_ENTRY_H1007_synchronousWindowLength &OD->list[5]
#define OD_ENTRY_H1010_storeParameters &OD->list[6]
#define OD_ENTRY_H1011_restoreDefaultParameters &OD->list[7]
#define OD_ENTRY_H1012_COB_IDTimeStampObject &OD->list[8]
#define OD_ENTRY_H1014_COB_ID_EMCY &OD->list[9]
#define OD_ENTRY_H1015_inhibitTimeEMCY &OD->list[10]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[11]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[12]
#define OD_ENTRY_H1018_identity &OD->list[13]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue &OD->list[14]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[15]
#define OD_ENTRY_H1280_SDOClientParameter &OD->list[16]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[17]
#define OD_ENTRY_H1401_RPDOCommunicationParameter &OD->list[18]
#define OD_ENTRY_H1402_RPDOCommunicationParameter &OD->list[19]
#define OD_ENTRY_H1403_RPDOCommunicationParameter &OD->list[20]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[21]
#define OD_ENTRY_H1601_RPDOMappingParameter &OD->list[22]
#define OD_ENTRY_H1602_RPDOMappingParameter &OD->list[23]
#define OD_ENTRY_H1603_RPDOMappingParameter &OD->list[24]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[25]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[26]
#define OD_ENTRY_H1802_TPDOCommunicationParameter &OD->list[27]
#define OD_ENTRY_H1803_TPDOCommunicationParameter &OD->list[28]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[29]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[30]
#define OD_ENTRY_H1A02_TPDOMappingParameter &OD->list[31]
#define OD_ENTRY_H1A03_TPDOMappingParameter &OD->list[32]
#define OD_ENTRY_H402C_directDataOperationOperationDataNumber &OD->list[33]
#define OD_ENTRY_H402D_directDataOperationOperationType &OD->list[34]
#define OD_ENTRY_H402E_directDataOperationPosition &OD->list[35]
#define OD_ENTRY_H402F_directDataOperationOperatingVelocity &OD->list[36]
#define OD_ENTRY_H4030_directDataOperationAccelerationRate &OD->list[37]
#define OD_ENTRY_H4031_directDataOperationDecelerationRate &OD->list[38]
#define OD_ENTRY_H4032_directDataOperationTorqueLimitingValue &OD->list[39]
#define OD_ENTRY_H4033_directDataOperationTrigger &OD->list[40]
#define OD_ENTRY_H4034_directDataOperationForwardingDestination &OD->list[41]
#define OD_ENTRY_H403A_driverInputCommand2nd &OD->list[42]
#define OD_ENTRY_H403C_driverInputCommandAutomaticOFF &OD->list[43]
#define OD_ENTRY_H403D_NETSelectionDataNumber &OD->list[44]
#define OD_ENTRY_H403E_driverInputCommand &OD->list[45]
#define OD_ENTRY_H403F_driverOutputStatus &OD->list[46]
#define OD_ENTRY_H404B_targetPositionUser_definedPositionUnit &OD->list[47]
#define OD_ENTRY_H404C_demandPositionUser_definedPositionUnit &OD->list[48]
#define OD_ENTRY_H404D_actualPositionUser_definedPositionUnit &OD->list[49]
#define OD_ENTRY_H404E_targetVelocityUser_definedVelocityUnit &OD->list[50]
#define OD_ENTRY_H404F_demandVelocityUser_definedVelocityUnit &OD->list[51]
#define OD_ENTRY_H4050_actualVelocityUser_definedVelocityUnit &OD->list[52]
#define OD_ENTRY_H4056_presentCommunicationError &OD->list[53]
#define OD_ENTRY_H406B_torqueMonitor &OD->list[54]
#define OD_ENTRY_H406C_loadFactorMonitor &OD->list[55]
#define OD_ENTRY_H406D_cumulativeLoadMonitor &OD->list[56]
#define OD_ENTRY_H4070_nextDataNumber &OD->list[57]
#define OD_ENTRY_H4071_loopOriginDataNumber &OD->list[58]
#define OD_ENTRY_H4072_loopCount &OD->list[59]
#define OD_ENTRY_H4073_positionDeviation &OD->list[60]
#define OD_ENTRY_H4075_speedDeviation &OD->list[61]
#define OD_ENTRY_H407A_tripmeter1 &OD->list[62]
#define OD_ENTRY_H407B_presentInformation &OD->list[63]
#define OD_ENTRY_H407C_driverTemperature &OD->list[64]
#define OD_ENTRY_H407D_motorTemperature &OD->list[65]
#define OD_ENTRY_H407E_odometer &OD->list[66]
#define OD_ENTRY_H407F_tripmeter0 &OD->list[67]
#define OD_ENTRY_H409B_mainPowerSupplyCurrent &OD->list[68]
#define OD_ENTRY_H409C_powerConsumption &OD->list[69]
#define OD_ENTRY_H409D_energyConsumption &OD->list[70]
#define OD_ENTRY_H409E_userEnergyConsumption &OD->list[71]
#define OD_ENTRY_H409F_totalEnergyConsumption &OD->list[72]
#define OD_ENTRY_H40A1_totalUptime &OD->list[73]
#define OD_ENTRY_H40A2_numberOfBoots &OD->list[74]
#define OD_ENTRY_H40A3_inverterVoltage &OD->list[75]
#define OD_ENTRY_H40A4_mainPowerSupplyVoltage &OD->list[76]
#define OD_ENTRY_H40A9_continuousUptime &OD->list[77]
#define OD_ENTRY_H40AA_RS_485CommunicationReceptionByteCounter &OD->list[78]
#define OD_ENTRY_H40AB_RS_485CommunicationTransmissionByteCounter &OD->list[79]
#define OD_ENTRY_H40C0_alarmReset &OD->list[80]
#define OD_ENTRY_H40C2_clearAlarmHistory &OD->list[81]
#define OD_ENTRY_H40C5_P_PRESETExecution &OD->list[82]
#define OD_ENTRY_H40C6_configuration &OD->list[83]
#define OD_ENTRY_H40CD_clearLatchInformation &OD->list[84]
#define OD_ENTRY_H40CE_clearSequenceHistory &OD->list[85]
#define OD_ENTRY_H40D0_clearETO &OD->list[86]
#define OD_ENTRY_H40D1_ZSG_PRESET &OD->list[87]
#define OD_ENTRY_H40D2_clearZSG_PRESET &OD->list[88]
#define OD_ENTRY_H40D3_clearInformation &OD->list[89]
#define OD_ENTRY_H40D6_clearUserEnergyConsumption &OD->list[90]
#define OD_ENTRY_H40D7_clearTripmeter0 &OD->list[91]
#define OD_ENTRY_H40D8_clearTripmeter1 &OD->list[92]
#define OD_ENTRY_H4148_permissionOfAbsolutePositioningWithoutSettingAbsoluteCoordinates &OD->list[93]
#define OD_ENTRY_H415F_JOG_HOME_TorqueLimitValue &OD->list[94]
#define OD_ENTRY_H4160_HOME_HomingMode &OD->list[95]
#define OD_ENTRY_H4163_HOME_StartingVelocity &OD->list[96]
#define OD_ENTRY_H4169_HOME_BackwardStepsIn2SensorHomeseeking &OD->list[97]
#define OD_ENTRY_H4186_stoppingTimeoutAtAlarmGeneration &OD->list[98]
#define OD_ENTRY_H41CA_WRAPSetting &OD->list[99]
#define OD_ENTRY_H4735_customStoppingRate &OD->list[100]
#define OD_ENTRY_H4736_customStoppingTime &OD->list[101]
#define OD_ENTRY_H603F_errorCode &OD->list[102]
#define OD_ENTRY_H6040_controlword &OD->list[103]
#define OD_ENTRY_H6041_statusword &OD->list[104]
#define OD_ENTRY_H605A_quickStopOptionCode &OD->list[105]
#define OD_ENTRY_H605B_shutdownOptionCode &OD->list[106]
#define OD_ENTRY_H605C_disableOperationOptionCode &OD->list[107]
#define OD_ENTRY_H605D_haltOptionCode &OD->list[108]
#define OD_ENTRY_H605E_faultReactionOptionCode &OD->list[109]
#define OD_ENTRY_H6060_modesOfOperation &OD->list[110]
#define OD_ENTRY_H6061_modesOfOperationDisplay &OD->list[111]
#define OD_ENTRY_H6062_positionDemandValue &OD->list[112]
#define OD_ENTRY_H6064_positionActualValue &OD->list[113]
#define OD_ENTRY_H6065_followingErrorWindow &OD->list[114]
#define OD_ENTRY_H6067_positionWindow &OD->list[115]
#define OD_ENTRY_H606B_velocityDemandValue &OD->list[116]
#define OD_ENTRY_H606C_velocityActualValue &OD->list[117]
#define OD_ENTRY_H606D_velocityWindow &OD->list[118]
#define OD_ENTRY_H606F_velocityThreshold &OD->list[119]
#define OD_ENTRY_H6072_maxTorque &OD->list[120]
#define OD_ENTRY_H6077_torqueActualValue &OD->list[121]
#define OD_ENTRY_H607A_targetPosition &OD->list[122]
#define OD_ENTRY_H607B_positionRangeLimit &OD->list[123]
#define OD_ENTRY_H607C_homeOffset &OD->list[124]
#define OD_ENTRY_H607D_softwarePositionLimit &OD->list[125]
#define OD_ENTRY_H6081_profileVelocity &OD->list[126]
#define OD_ENTRY_H6082_endVelocity &OD->list[127]
#define OD_ENTRY_H6083_profileAcceleration &OD->list[128]
#define OD_ENTRY_H6084_profileDeceleration &OD->list[129]
#define OD_ENTRY_H6085_quickStopDeceleration &OD->list[130]
#define OD_ENTRY_H608F_positionEncoderResolution &OD->list[131]
#define OD_ENTRY_H6091_gearRatio &OD->list[132]
#define OD_ENTRY_H6098_homingMethod &OD->list[133]
#define OD_ENTRY_H6099_homingSpeeds &OD->list[134]
#define OD_ENTRY_H609A_homingAcceleration &OD->list[135]
#define OD_ENTRY_H60A8_SIUnitPosition &OD->list[136]
#define OD_ENTRY_H60A9_SIUnitVelocity &OD->list[137]
#define OD_ENTRY_H60B8_touchProbeFunction &OD->list[138]
#define OD_ENTRY_H60B9_touchProbeStatus &OD->list[139]
#define OD_ENTRY_H60BA_touchProbe1PositiveEdge &OD->list[140]
#define OD_ENTRY_H60BB_touchProbe1NegativeEdge &OD->list[141]
#define OD_ENTRY_H60BC_touchProbe2PositiveEdge &OD->list[142]
#define OD_ENTRY_H60BD_touchProbe2NegativeEdge &OD->list[143]
#define OD_ENTRY_H60D5_touchProbe1PositiveEdgeCounter &OD->list[144]
#define OD_ENTRY_H60D6_touchProbe1NegativeEdgeCounter &OD->list[145]
#define OD_ENTRY_H60D7_touchProbe2PositiveEdgeCounter &OD->list[146]
#define OD_ENTRY_H60D8_touchProbe2NegativeEdgeCounter &OD->list[147]
#define OD_ENTRY_H60E3_supportedHomingMethods &OD->list[148]
#define OD_ENTRY_H60F2_positioningOptionCode &OD->list[149]
#define OD_ENTRY_H60F4_followingErrorActualValue &OD->list[150]
#define OD_ENTRY_H60FD_digitalInputs &OD->list[151]
#define OD_ENTRY_H60FE_digitalOutputs &OD->list[152]
#define OD_ENTRY_H60FF_targetVelocity &OD->list[153]
#define OD_ENTRY_H6502_supportedDriveModes &OD->list[154]
#define OD_ENTRY_H67FE_versionNumber &OD->list[155]
#define OD_ENTRY_H67FF_singleDeviceType &OD->list[156]
#define OD_ENTRY_H6FFF_agvOdometry &OD->list[157]
#define OD_ENTRY_H7000_agvCmdVel &OD->list[158]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
